defmodule Driver.CampaignStagesTest do
  # Stage logic against ScriptedBoard: board interactions scripted and
  # recorded, local evidence layout real (tmp_dir). async: false — the
  # recorder is a named Agent and the guard stub reads a global env var.
  use ExUnit.Case, async: false

  alias Driver.Campaign
  alias Driver.Campaign.Config
  alias Driver.ScriptedBoard

  @moduletag :tmp_dir
  @moduletag :capture_log

  setup %{tmp_dir: tmp} do
    qdq_dir = Path.join(tmp, "qdq")
    out = Path.join(tmp, "out")
    File.mkdir_p!(qdq_dir)
    File.mkdir_p!(out)

    # The retry guard's rc contract (0 skip / 4 rerun / other fatal),
    # driven per-test via FAKE_GUARD_RC.
    File.write!(Path.join(qdq_dir, "campaign_meta.py"), """
    import os, sys
    sys.exit(int(os.environ.get("FAKE_GUARD_RC", "4")))
    """)

    File.write!(Path.join(qdq_dir, "htp_content_test.sh"), "#!/bin/sh\n# fixture\n")

    on_exit(fn -> System.delete_env("FAKE_GUARD_RC") end)

    cfg =
      Config.new(
        qdq_dir: qdq_dir,
        out: out,
        board: ScriptedBoard,
        bench_dir: Path.join(tmp, "board-bench"),
        clip_dir: Path.join(tmp, "board-data"),
        reboot_opts: [settle_ms: 0]
      )

    {:ok, cfg: cfg, qdq_dir: qdq_dir, out: out}
  end

  defp start_board!(script \\ %{}) do
    start_supervised!({ScriptedBoard, script})
    ScriptedBoard.session()
  end

  defp write_artifacts!(cfg) do
    File.mkdir_p!(Config.art(cfg))
    File.mkdir_p!(Path.join(cfg.out, "records"))

    record_lines =
      for {name, _, _} <- Config.rungs() do
        path = Path.join(Config.art(cfg), "#{name}.onnx")
        File.write!(path, "onnx:#{name}")
        sha = :crypto.hash(:sha256, "onnx:#{name}") |> Base.encode16(case: :lower)
        "#{sha}  #{name}.onnx"
      end

    File.write!(
      Path.join([cfg.out, "records", "artifacts.sha256"]),
      Enum.join(record_lines, "\n") <> "\n"
    )
  end

  describe "push" do
    test "pushes script + 12 artifacts and records pushed.sha256 for the analyzer",
         %{cfg: cfg} do
      write_artifacts!(cfg)
      pushed_listing = "abc123  #{cfg.bench_dir}/artifacts-fixed/yolox_nano-qdq-a16.onnx\n"
      board = start_board!(%{cmd: fn _, "sha256sum " <> _, _ -> {pushed_listing, 0} end})

      assert {:ok, _} = Campaign.run(:push, board, cfg)

      writes = ScriptedBoard.calls(:write!)
      assert length(writes) == 13
      assert [{:write!, [_, _, dest]} | _] = writes
      assert dest == Path.join(cfg.bench_dir, "htp_content_test.sh")
      # htp_report.py authenticates latency rows against this file.
      assert File.read!(Path.join(Config.htp(cfg), "pushed.sha256")) == pushed_listing
    end

    test "an unreadable board-side sha listing fails the push", %{cfg: cfg} do
      write_artifacts!(cfg)
      board = start_board!(%{cmd: fn _, "sha256sum " <> _, _ -> {"boom", 2} end})

      assert {:error, {:pushed_sha_unreadable, 2, "boom"}} = Campaign.run(:push, board, cfg)
    end

    test "refuses up front when a local artifact is missing", %{cfg: cfg} do
      write_artifacts!(cfg)
      File.rm!(Path.join(Config.art(cfg), "yolox_s-qdq-a8.onnx"))
      board = start_board!()

      assert {:error, {:missing_local_files, [missing]}} = Campaign.run(:push, board, cfg)
      assert missing =~ "yolox_s-qdq-a8.onnx"
      assert ScriptedBoard.calls(:write!) == []
    end

    test "refuses when local bytes drifted from the record", %{cfg: cfg} do
      write_artifacts!(cfg)
      File.write!(Path.join(Config.art(cfg), "yolox_m-qdq-a16.onnx"), "regenerated bytes")
      board = start_board!()

      assert {:error, {:artifact_record_mismatch, [{"yolox_m-qdq-a16.onnx", _, _}]}} =
               Campaign.run(:push, board, cfg)

      assert ScriptedBoard.calls(:write!) == []
    end
  end

  describe "envcheck" do
    defp spike_output(cpu, qnn) do
      """
      [DSP] noisy line
      {"ep": "cpu", "p50_ms": #{cpu}}
      more noise
      {"ep": "qnn", "p50_ms": #{qnn}}
      """
    end

    test "passes in the phase-0 regime and saves the spike output", %{cfg: cfg} do
      out = spike_output(38.2, 6.5)
      board = start_board!(%{cmd: fn _, _, _ -> {out, 0} end})

      assert {:ok, _} = Campaign.run(:envcheck, board, cfg)
      assert File.read!(Path.join(Config.htp(cfg), "spike-env.txt")) == out
      assert [{:engine_stop, _}] = ScriptedBoard.calls(:engine_stop)
    end

    test "fails out of regime, and fail-closed on missing numbers", %{cfg: cfg} do
      board = start_board!(%{cmd: fn _, _, _ -> {spike_output(38.2, 20.0), 0} end})
      assert {:error, :envcheck_failed} = Campaign.run(:envcheck, board, cfg)

      # No parseable p50 lines at all must read FAIL, never PASS.
      restart_board!(%{cmd: fn _, _, _ -> {"only noise\n", 0} end})
      assert {:error, :envcheck_failed} = Campaign.run(:envcheck, ScriptedBoard.session(), cfg)
    end

    test "a nonzero spike rc is its own error", %{cfg: cfg} do
      board = start_board!(%{cmd: fn _, _, _ -> {"boom", 3} end})
      assert {:error, {:spike_failed, 3, "boom"}} = Campaign.run(:envcheck, board, cfg)
    end
  end

  describe "content" do
    test "charges the QNN budget and reboots at the ceiling", %{cfg: cfg} do
      System.put_env("FAKE_GUARD_RC", "4")
      cfg = %{cfg | clips: ["ac86"], qnn_session_budget: 5}

      board =
        start_board!(%{
          cmd: fn _, sh, _ ->
            if sh =~ "sha256sum", do: {"#{cfg.old_nano_sha}  ctl.onnx", 0}, else: {"", 0}
          end
        })

      assert {:ok, final} = Campaign.run(:content, board, cfg)

      # 12 rung runs + 1 control run charge the budget; the ort control
      # does not. Budget 5: leading reboot + one at each 5-session wall.
      assert length(ScriptedBoard.calls(:reboot)) == 1 + div(13 - 1, 5)
      assert final.qnn_sessions == rem(13 - 1, 5) + 1
      assert length(ScriptedBoard.calls(:engine_stop)) == 14
    end

    test "skips everything the retry guard vouches for", %{cfg: cfg} do
      System.put_env("FAKE_GUARD_RC", "0")
      cfg = %{cfg | clips: ["ac86"]}

      board =
        start_board!(%{
          cmd: fn _, sh, _ ->
            if sh =~ "sha256sum", do: {"#{cfg.old_nano_sha}  ctl.onnx", 0}, else: {"", 0}
          end
        })

      assert {:ok, _} = Campaign.run(:content, board, cfg)
      # Reboot + pin still happen; no run is executed or engine-stopped.
      assert ScriptedBoard.calls(:engine_stop) == []
      assert length(ScriptedBoard.calls(:pin_governor)) == 1
    end

    test "a broken guard is fatal, never a blind rerun", %{cfg: cfg} do
      System.put_env("FAKE_GUARD_RC", "7")
      cfg = %{cfg | clips: ["ac86"]}
      board = start_board!()

      assert {:error, {:retry_guard_broken, 7, _}} = Campaign.run(:content, board, cfg)
    end

    test "a run that raises (erpc timeout, node down mid-call) warns and continues",
         %{cfg: cfg} do
      System.put_env("FAKE_GUARD_RC", "4")
      cfg = %{cfg | clips: ["ac86"]}

      board =
        start_board!(%{
          cmd: fn
            _, "sha256sum " <> _, _ -> {"#{cfg.old_nano_sha}  ctl.onnx", 0}
            _, sh, _ -> if sh =~ "htp_content_test.sh", do: raise("erpc timeout"), else: {"", 0}
          end
        })

      # All 14 runs raise; bash's `timeout ... || log WARN` semantics say
      # the campaign keeps going — the truth is checked on fetch.
      assert {:ok, _} = Campaign.run(:content, board, cfg)
      assert length(ScriptedBoard.calls(:engine_stop)) == 14
    end

    test "refuses a control that is not the shipped defective nano", %{cfg: cfg} do
      System.put_env("FAKE_GUARD_RC", "0")
      cfg = %{cfg | clips: ["ac86"]}

      board =
        start_board!(%{
          cmd: fn _, sh, _ ->
            if sh =~ "sha256sum", do: {"deadbeef  ctl.onnx", 0}, else: {"", 0}
          end
        })

      assert {:error, {:control_bytes_not_defective_nano, _}} =
               Campaign.run(:content, board, cfg)
    end
  end

  describe "latency" do
    test "board-sourced start marker; nonzero bench rc warns but continues", %{cfg: cfg} do
      board =
        start_board!(%{
          cmd: fn _, sh, _ ->
            cond do
              sh == "date +%s" -> {"1234567\n", 0}
              sh =~ "yolox_tiny-qdq-a8" -> {"", 1}
              true -> {"", 0}
            end
          end
        })

      assert {:ok, _} = Campaign.run(:latency, board, cfg)
      assert File.read!(Path.join(Config.htp(cfg), ".latency-start")) == "1234567\n"

      bench_cmds = for {:cmd, [_, sh, _]} <- ScriptedBoard.calls(:cmd), sh =~ "bench.sh", do: sh
      assert length(bench_cmds) == 13
      assert List.last(bench_cmds) =~ "ort 60 1"
    end
  end

  describe "fetch" do
    test "mirrors content and only new bench runs", %{cfg: cfg, tmp_dir: tmp} do
      # "Board" files live in tmp; eval! lists them, read! serves them.
      board_content = Path.join(cfg.bench_dir, "content/tag1")
      File.mkdir_p!(board_content)
      File.write!(Path.join(board_content, "meta.json"), ~s({"tag": "tag1"}))
      run_new = Path.join(cfg.bench_dir, "runs/bench-150")
      File.mkdir_p!(run_new)
      File.write!(Path.join(run_new, "stats.txt"), "p50 1.0")

      File.mkdir_p!(Config.htp(cfg))
      File.write!(Path.join(Config.htp(cfg), ".latency-start"), "100\n")

      board =
        start_board!(%{
          cmd: fn _, "ls " <> _, _ -> {"bench-50\nbench-150\nnot-a-run\n", 0} end,
          eval!: fn _, _, binding ->
            dir = Keyword.fetch!(binding, :dir)

            Path.wildcard(Path.join(dir, "**"))
            |> Enum.map(&{&1, File.dir?(&1)})
          end,
          read!: fn _, path, _ -> File.read!(path) end
        })

      assert {:ok, _} = Campaign.run(:fetch, board, cfg)

      assert File.read!(Path.join(Config.htp(cfg), "content/tag1/meta.json")) =~ "tag1"
      assert File.exists?(Path.join(Config.htp(cfg), "runs/bench-150/stats.txt"))
      # bench-50 predates the marker; a name without a timestamp is skipped.
      refute File.exists?(Path.join(Config.htp(cfg), "runs/bench-50"))
      refute File.exists?(Path.join(Config.htp(cfg), "runs/not-a-run"))
      _ = tmp
    end

    test "no latency marker means no bench-run pull", %{cfg: cfg} do
      board = start_board!(%{cmd: fn _, "ls " <> _, _ -> {"bench-150\n", 0} end})
      assert {:ok, _} = Campaign.run(:fetch, board, cfg)
      refute File.exists?(Path.join(Config.htp(cfg), "runs/bench-150"))
    end
  end

  describe "finish" do
    test "restores, restarts, reboots — and clears the pin marker", %{cfg: cfg} do
      File.mkdir_p!(Config.htp(cfg))
      marker = Path.join(Config.htp(cfg), ".gov-pinned")
      File.write!(marker, "schedutil\n")

      board = start_board!(%{restore_governor: fn _ -> {:ok, {:restored, "schedutil"}} end})

      assert {:ok, _} = Campaign.run(:finish, board, cfg)
      refute File.exists?(marker)
      assert [{:final_reboot, _}] = ScriptedBoard.calls(:final_reboot)
    end

    test "pinned this campaign but nothing saved is fatal, and the reboot still runs",
         %{cfg: cfg} do
      File.mkdir_p!(Config.htp(cfg))
      File.write!(Path.join(Config.htp(cfg), ".gov-pinned"), "schedutil\n")

      board = start_board!(%{restore_governor: fn _ -> {:ok, :nothing_to_restore} end})

      assert {:error, {:finish_incomplete, reasons}} = Campaign.run(:finish, board, cfg)
      assert :pinned_but_nothing_saved in reasons
      assert [{:final_reboot, _}] = ScriptedBoard.calls(:final_reboot)
    end

    test "without a pin marker, nothing-to-restore is the no-op path", %{cfg: cfg} do
      board = start_board!()
      assert {:ok, _} = Campaign.run(:finish, board, cfg)
    end

    test "cleanup failures are collected, not shadowed", %{cfg: cfg} do
      board =
        start_board!(%{
          engine_start: fn _, _ -> {:error, :nope} end,
          final_reboot: fn _, _ -> {:error, :reboot_not_observed} end
        })

      assert {:error, {:finish_incomplete, reasons}} = Campaign.run(:finish, board, cfg)
      assert {:engine_start, :nope} in reasons
      assert :final_reboot_not_observed in reasons
    end
  end

  describe "CLI finish trap" do
    test "a failing trapped stage still ends in finish", %{cfg: cfg} do
      System.put_env("FAKE_GUARD_RC", "7")
      start_board!()

      assert {:error, {{:content, {:retry_guard_broken, 7, _}}, _}} =
               err_with_finish(Driver.CLI.run([:content], cfg))

      assert [{:final_reboot, _}] = ScriptedBoard.calls(:final_reboot)
    end

    test "a stage that RAISES still reaches the finish trap", %{cfg: cfg} do
      start_board!(%{engine_stop: fn _, _ -> raise "node vanished mid-call" end})

      assert {:error, {{:envcheck, {:raised, %RuntimeError{}}}, _}} =
               err_with_finish(Driver.CLI.run([:envcheck], cfg))

      assert [{:final_reboot, _}] = ScriptedBoard.calls(:final_reboot)
    end

    test "untrapped stages do not drag finish in", %{cfg: cfg} do
      write_artifacts!(cfg)
      start_board!()

      assert :ok = Driver.CLI.run([:push], cfg)
      assert ScriptedBoard.calls(:final_reboot) == []
    end

    test "the manual reboot stage runs alone, no trap", %{cfg: cfg} do
      start_board!()

      assert Driver.CLI.parse(["reboot"]) == {:ok, [:reboot]}
      assert :ok = Driver.CLI.run([:reboot], cfg)
      assert length(ScriptedBoard.calls(:reboot)) == 1
      assert ScriptedBoard.calls(:final_reboot) == []
    end
  end

  defp restart_board!(script) do
    stop_supervised!(ScriptedBoard)
    start_supervised!({ScriptedBoard, script})
  end

  # The trap either succeeds (error stays bare) or fails (pair) — accept both.
  defp err_with_finish({:error, {stage_reason, {:finish_also_failed, _}}}),
    do: {:error, {stage_reason, :finish_failed}}

  defp err_with_finish({:error, stage_reason}), do: {:error, {stage_reason, :finish_ok}}
end
