import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :cairn, CairnWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# No force_ssl: cairn's v1 posture is LAN-trusted plain http (no TLS
# terminator anywhere in the deployment), and the generator's hardened
# default 301'd every non-localhost request — including the vagus panel's
# webui link to host:4000 — at an https listener that doesn't exist.
# Device-proven on the Q6A.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
